const QUESTIONS=[
{name:'THE FIRST DOOR',q:'You can know the truth, but it will destroy your peace. Do you open it?',a:[['Open it. A comfortable lie is still a lie.',{truth:3,curiosity:2,peace:-2}],['Leave it closed. Some truths are not worth their price.',{peace:3,safety:1,truth:-2}],['Open it when I am ready to carry it.',{reason:2,truth:1,peace:1}]]},
{name:'THE EMPTY ROOM',q:'A perfect life is offered to you, but none of it is real. Would you stay?',a:[['Yes. If I can feel it, why does reality matter?',{peace:3,truth:-3}],['No. I would rather suffer inside reality.',{truth:3,freedom:2,peace:-1}],['For a while. I need to know what the illusion reveals.',{curiosity:3,reason:1}]]},
{name:'THE SCALE',q:'Five strangers can live if one person you love dies. Who decides?',a:[['The numbers. Five lives outweigh one.',{reason:3,mercy:-2}],['I refuse to turn love into arithmetic.',{mercy:3,reason:-2}],['I would offer myself instead.',{sacrifice:3,mercy:2}]]},
{name:'THE CAGE',q:'If every choice you make was shaped by your past, are you truly free?',a:[['Freedom begins when I recognize the cage.',{freedom:3,curiosity:1}],['Freedom is an illusion, but I will live as if it is real.',{reason:2,freedom:-1}],['I do not need an answer to act freely.',{freedom:2,reason:1}]]},
{name:'THE MIRROR',q:'Your memories are changing every time you remember them. Which version is you?',a:[['The story I choose to keep.',{identity:3,freedom:1}],['None. Memory is evidence, not identity.',{reason:3,truth:2}],['The people who remember me.',{mercy:2,identity:2}]]},
{name:'THE CROWN',q:'You are offered absolute power to make the world better. Do you take it?',a:[['Yes. Leaving power to worse people is irresponsible.',{power:3,reason:1}],['No. No one should hold absolute power.',{freedom:3,ethics:3,power:-3}],['I take it only to dismantle it.',{ethics:2,sacrifice:2,power:-1}]]},
{name:'THE ABYSS',q:'One fact could collapse everything your life is built on. Do you read it?',a:[['Yes. A life built on falsehood is already broken.',{truth:3,curiosity:2,safety:-2}],['No. Some structures protect the person inside them.',{safety:3,peace:1,truth:-2}],['I prepare myself first, then read.',{reason:2,safety:1,truth:1}]]},
{name:'THE GARDEN',q:'You can erase one regret, but every lesson born from it disappears too. Do you erase it?',a:[['Yes. Pain is not sacred.',{peace:3,mercy:1,identity:-1}],['No. I became someone through that wound.',{identity:3,truth:1,peace:-1}],['I would keep the lesson and lose the memory if possible.',{reason:2,curiosity:1}]]},
{name:'THE BRIDGE',q:'A stranger is falling. Saving them will destroy the one opportunity you have waited years for.',a:[['Save them. A life outranks my ambition.',{mercy:3,sacrifice:2,ambition:-2}],['Take the opportunity. I cannot save everyone.',{reason:2,ambition:3,mercy:-1}],['Try to save them without surrendering the opportunity.',{curiosity:2,reason:1,ambition:1}]]},
{name:'THE CLOCK',q:'You can learn the exact moment of your death. Knowledge or ignorance?',a:[['Tell me. I would rather prepare than wonder.',{truth:3,reason:1,peace:-1}],['Never. Uncertainty gives tomorrow its shape.',{peace:3,freedom:1,curiosity:-1}],['Only if I cannot tell anyone else.',{curiosity:3,identity:1}]]},
{name:'THE SHIP',q:'Every part of you is gradually replaced until nothing biological remains. Are you still you?',a:[['Yes. Continuity is enough.',{identity:3,reason:1}],['No. There must be an original self.',{truth:2,identity:-1}],['The question proves identity is a story, not an object.',{curiosity:3,identity:2}]]},
{name:'THE LAST DOOR',q:'After everything you chose here, did you choose your answers—or did they reveal you?',a:[['I chose. The maze only gave me the doors.',{freedom:3,identity:2}],['They revealed me. The maze was a mirror.',{truth:3,reason:2}],['Choice and revelation are the same thing.',{curiosity:3,identity:2,reason:1}]]}
];
const ENDINGS={truth:['THE TRUTH SEEKER','You would rather lose comfort than build a life on something you cannot trust.'],freedom:['THE UNBOUND MIND','You instinctively question cages, rules and inherited answers. Freedom is not comfort to you; it is authorship.'],reason:['THE RATIONALIST','You dissect the question before accepting its frame. Your strength is clarity—and your danger is believing everything important can be measured.'],mercy:['THE COMPASSIONATE','You notice the human cost behind every abstraction. You may sacrifice efficiency to preserve someone’s humanity.'],curiosity:['THE ETERNAL SEEKER','Answers close doors; questions open them. You are most alive when certainty starts to crack.'],power:['THE KEEPER OF ORDER','You see responsibility where others see control. Your challenge is knowing when order has become a cage.'],sacrifice:['THE MARTYR','When the price must be paid, you often volunteer yourself. Your strength is devotion; your danger is forgetting your own worth.'],peace:['THE QUIET SOUL','You understand that not every truth must be chased and not every battle must be fought. You value a life that can still breathe.'],identity:['THE STORYMAKER','You believe a person is more than facts: identity is the story, memory and meaning we carry forward.'],ethics:['THE CONSCIENCE','You resist convenient answers when they violate a principle. You would rather pay a cost than call wrong right.'],safety:['THE SHELTERER','You protect continuity, stability and the people inside your circle. Your challenge is knowing when safety becomes a prison.'],ambition:['THE ASCENDER','You are willing to risk comfort for a larger horizon. Your challenge is remembering that a destination cannot justify every road.']};
