(()=>{
'use strict';
const canvas=document.getElementById('world'),ctx=canvas.getContext('2d'),map=document.getElementById('map'),mctx=map.getContext('2d');
const $=id=>document.getElementById(id);const mindEl=$('mind'),doorsEl=$('doors'),hint=$('hint'),interaction=$('interaction'),objective=$('objective'),modal=$('question-modal'),answers=$('answers'),doorName=$('door-name'),question=$('question'),ending=$('ending'),endingTitle=$('ending-title'),endingText=$('ending-text'),endingStats=$('ending-stats'),endingDetail=$('ending-detail'),dialogue=$('dialogue'),dialogueText=$('dialogue-text'),journal=$('journal'),journalText=$('journal-text'),signals=$('signals');
let W=innerWidth,H=innerHeight,dpr=Math.min(devicePixelRatio||1,2);const world={w:3200,h:2300};const player={x:1600,y:1900,r:15,speed:3.7};
const keys=new Set();let activeDoor=null,completed=0,mind=50,startedAt=performance.now(),dialogueIndex=0,dialogueOpen=false;const scores={},answersChosen=[];
const doors=[
{x:1600,y:1580,q:0,zone:'THE THRESHOLD'},{x:900,y:1160,q:1,zone:'THE EMPTY QUARTER'},{x:2300,y:1120,q:2,zone:'THE SCALE'},{x:520,y:1780,q:3,zone:'THE CAGE'},
{x:2680,y:1780,q:4,zone:'THE MIRROR GARDEN'},{x:720,y:480,q:5,zone:'THE CROWN'},{x:2460,y:450,q:6,zone:'THE ABYSS'},{x:1600,y:300,q:7,zone:'THE GARDEN'},
{x:420,y:700,q:8,zone:'THE BRIDGE'},{x:2800,y:700,q:9,zone:'THE CLOCK'},{x:1600,y:720,q:10,zone:'THE SHIP'},{x:1600,y:80,q:11,zone:'THE LAST DOOR'}];
const walls=[{x:1450,y:1750,w:300,h:70},{x:400,y:1350,w:900,h:70},{x:1900,y:1350,w:900,h:70},{x:1050,y:700,w:1100,h:70},{x:1050,y:900,w:70,h:600},{x:2080,y:900,w:70,h:600},{x:300,y:300,w:70,h:700},{x:2830,y:300,w:70,h:700}];
const trees=[];for(let i=0;i<75;i++){let x=120+((i*487)%2960),y=120+((i*733)%2050);if(Math.hypot(x-player.x,y-player.y)>220)trees.push({x,y,r:12+(i%3)*4})}
const oldMan={x:1600,y:2080,r:16};
const shards=[{x:300,y:2050,used:false},{x:2910,y:1960,used:false},{x:340,y:1180,used:false},{x:2860,y:1180,used:false},{x:900,y:250,used:false},{x:2300,y:250,used:false}];
function resize(){W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}resize();addEventListener('resize',resize);
function blocked(x,y){if(x<40||y<40||x>world.w-40||y>world.h-40)return true;for(const w of walls){const nx=Math.max(w.x,Math.min(x,w.x+w.w)),ny=Math.max(w.y,Math.min(y,w.y+w.h));if(Math.hypot(x-nx,y-ny)<player.r+4)return true}for(const t of trees){if(Math.hypot(x-t.x,y-t.y)<player.r+t.r-3)return true}return false}
function nearDoor(){let best=null,dist=Infinity;for(const d of doors)if(!d.done){const z=Math.hypot(player.x-d.x,player.y-d.y);if(z<dist){dist=z;best=d}}return dist<105?best:null}
function nearMan(){return Math.hypot(player.x-oldMan.x,player.y-oldMan.y)<125}
function nearShard(){return shards.find(s=>!s.used&&Math.hypot(player.x-s.x,player.y-s.y)<55)}
function openDoor(d){activeDoor=d;const q=QUESTIONS[d.q];doorName.textContent=q.name;question.textContent=q.q;answers.innerHTML='';q.a.forEach((item,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=item[0];b.onclick=()=>choose(i);answers.appendChild(b)});modal.classList.remove('hidden');hint.classList.add('hidden');interaction.classList.add('hidden')}
function choose(i){const q=QUESTIONS[activeDoor.q],choice=q.a[i],v=choice[1];answersChosen.push({q:q.name,i});for(const[k,n]of Object.entries(v))scores[k]=(scores[k]||0)+n;mind=Math.max(0,Math.min(100,mind+(v.peace||0)-(v.truth<0?2:0)+(v.mercy||0)*.2));activeDoor.done=true;completed++;doorsEl.textContent=`${completed} / ${doors.length}`;mindEl.textContent=Math.round(mind);objective.textContent=completed<doors.length?`The maze has remembered ${completed} choice${completed===1?'':'s'}. Find another door.`:'Every door has been opened. The maze is ready to speak.';updateJournal();modal.classList.add('hidden');activeDoor=null;if(completed===doors.length)setTimeout(showEnding,650)}
function showEnding(){let sorted=Object.entries(scores).sort((a,b)=>b[1]-a[1]),best=sorted[0]||['curiosity',0];let e=ENDINGS[best[0]]||ENDINGS.curiosity;endingTitle.textContent=e[0];endingText.textContent=e[1];endingStats.innerHTML=`<div><b>${completed}</b><span>doors crossed</span></div><div><b>${Math.round(best[1])}</b><span>dominant signal</span></div><div><b>${Math.round(mind)}</b><span>mind</span></div>`;endingDetail.textContent=`Strongest signals: ${sorted.slice(0,3).map(x=>x[0]).join(' · ')}. This is a reflection, not a diagnosis.`;ending.classList.remove('hidden')}
function updateJournal(){let sorted=Object.entries(scores).sort((a,b)=>b[1]-a[1]);journalText.textContent=completed?`Door ${completed} left a mark. The maze is beginning to recognize a pattern in you.`:'The maze has not learned your shape yet.';signals.innerHTML=sorted.slice(0,4).map(([k,v])=>`<div class="signal"><span>${k}</span><i><b style="width:${Math.min(100,Math.max(5,v*12))}%"></b></i></div>`).join('')}
function openDialogue(){if(dialogueOpen)return;dialogueOpen=true;dialogueIndex=(completed+answersChosen.length)%NPC_LINES.length;dialogueText.textContent=NPC_LINES[dialogueIndex];dialogue.classList.remove('hidden');interaction.classList.add('hidden')}
function closeDialogue(){dialogue.classList.add('hidden');dialogueOpen=false}
$('dialogue-next').onclick=()=>{if(dialogueIndex<NPC_LINES.length-1){dialogueIndex++;dialogueText.textContent=NPC_LINES[dialogueIndex]}else closeDialogue()};
$('restart').onclick=()=>location.reload();
$('close-journal').onclick=()=>journal.classList.toggle('hidden');
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='m'){journal.classList.toggle('hidden');return}if(k==='escape'){if(!dialogue.classList.contains('hidden'))closeDialogue();else if(!modal.classList.contains('hidden')){modal.classList.add('hidden');activeDoor=null}return}keys.add(k);if(k==='e'&&!activeDoor&&modal.classList.contains('hidden')&&ending.classList.contains('hidden')){const d=nearDoor();if(d)openDoor(d);else if(nearMan())openDialogue();else{const s=nearShard();if(s){s.used=true;mind=Math.min(100,mind+3);mindEl.textContent=Math.round(mind);objective.textContent='You found a memory fragment. It was not yours—or perhaps it was.';updateJournal()}}}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();keys.add(k)});['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>keys.delete(k)))})
function update(){if(!modal.classList.contains('hidden')||!ending.classList.contains('hidden')||dialogueOpen)return;let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(dx||dy){let n=Math.hypot(dx,dy),nx=player.x+dx/n*player.speed,ny=player.y+dy/n*player.speed;if(!blocked(nx,player.y))player.x=nx;if(!blocked(player.x,ny))player.y=ny}const d=nearDoor(),m=nearMan(),s=nearShard();if(d){interaction.classList.remove('hidden');interaction.innerHTML=`Press <b>E</b> to enter <span>· ${d.zone}</span>`}else if(m){interaction.classList.remove('hidden');interaction.innerHTML=`Press <b>E</b> to speak <span>· THE OLD MAN</span>`}else if(s){interaction.classList.remove('hidden');interaction.innerHTML=`Press <b>E</b> to collect <span>· MEMORY FRAGMENT</span>`}else interaction.classList.add('hidden')}
function dominant(){const a=Object.entries(scores).sort((x,y)=>y[1]-x[1])[0];return a?a[0]:''}
function drawWorld(){ctx.fillStyle='#070911';ctx.fillRect(0,0,world.w,world.h);for(let x=0;x<world.w;x+=80)for(let y=0;y<world.h;y+=80){ctx.fillStyle=((x+y)/80%2?'#0a0c14':'#090b12');ctx.fillRect(x,y,78,78)}
ctx.fillStyle='#0d101b';ctx.fillRect(1320,0,560,2300);ctx.fillRect(0,1010,3200,310);ctx.fillStyle='#111524';ctx.fillRect(1480,0,240,2300);ctx.fillRect(0,1120,3200,90);
ctx.strokeStyle='#1b1e2d';ctx.lineWidth=2;for(let x=40;x<world.w;x+=80){ctx.beginPath();ctx.moveTo(x,40);ctx.lineTo(x,world.h-40);ctx.stroke()}for(let y=40;y<world.h;y+=80){ctx.beginPath();ctx.moveTo(40,y);ctx.lineTo(world.w-40,y);ctx.stroke()}
for(const w of walls){ctx.fillStyle='#171a29';ctx.fillRect(w.x,w.y,w.w,w.h);ctx.strokeStyle='#2c2b40';ctx.strokeRect(w.x,w.y,w.w,w.h)}
for(const t of trees){ctx.fillStyle='#0e1718';ctx.beginPath();ctx.arc(t.x,t.y,t.r+7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#172622';ctx.beginPath();ctx.arc(t.x,t.y,t.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#2b342d';ctx.fillRect(t.x-2,t.y+t.r-2,4,11)}
for(const s of shards)if(!s.used){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(performance.now()/900);ctx.shadowBlur=18;ctx.shadowColor='#8b78df';ctx.fillStyle='#8b78df';ctx.beginPath();ctx.moveTo(0,-9);ctx.lineTo(6,0);ctx.lineTo(0,9);ctx.lineTo(-6,0);ctx.closePath();ctx.fill();ctx.restore()}
for(const d of doors){ctx.save();ctx.translate(d.x,d.y);const glow=d.done?'#55566b':(dominant()&&d.q<=completed?'#8b78df':'#cba94f');ctx.shadowBlur=d.done?7:32;ctx.shadowColor=glow;ctx.fillStyle=d.done?'#292b36':'#8e7435';ctx.fillRect(-25,-42,50,84);ctx.fillStyle=d.done?'#0f1119':'#12131c';ctx.fillRect(-18,-34,36,68);ctx.strokeStyle=glow;ctx.strokeRect(-18,-34,36,68);ctx.fillStyle=d.done?'#777':'#e4cf8c';ctx.beginPath();ctx.arc(10,4,4,0,Math.PI*2);ctx.fill();ctx.restore()}
ctx.save();ctx.translate(oldMan.x,oldMan.y);ctx.shadowBlur=22;ctx.shadowColor='#cba94f';ctx.fillStyle='#5e5361';ctx.beginPath();ctx.arc(0,0,oldMan.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d5c5a0';ctx.beginPath();ctx.arc(0,-10,9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#17141c';ctx.fillRect(-10,-1,20,16);ctx.restore();
ctx.save();ctx.translate(player.x,player.y);ctx.shadowBlur=26;ctx.shadowColor='#8b78df';ctx.fillStyle='#ddd7c9';ctx.beginPath();ctx.arc(0,0,player.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#8b78df';ctx.beginPath();ctx.arc(0,-3,8,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawMap(){mctx.clearRect(0,0,180,130);mctx.fillStyle='#080a12';mctx.fillRect(0,0,180,130);const sx=180/world.w,sy=130/world.h;mctx.fillStyle='#151827';for(const w of walls)mctx.fillRect(w.x*sx,w.y*sy,w.w*sx,w.h*sy);for(const d of doors){mctx.fillStyle=d.done?'#555':'#cba94f';mctx.fillRect(d.x*sx-2,d.y*sy-2,4,4)}mctx.fillStyle='#cba94f';mctx.fillRect(oldMan.x*sx-2,oldMan.y*sy-2,4,4);mctx.fillStyle='#9a88ed';mctx.beginPath();mctx.arc(player.x*sx,player.y*sy,3,0,Math.PI*2);mctx.fill()}
function frame(){update();ctx.clearRect(0,0,W,H);const camX=Math.max(0,Math.min(world.w-W,player.x-W/2)),camY=Math.max(0,Math.min(world.h-H,player.y-H/2));ctx.save();ctx.translate(-camX,-camY);drawWorld();ctx.restore();drawMap();requestAnimationFrame(frame)}
updateJournal();frame();
})();
