const KEY='story-forge-v3';
const DEFAULT={characters:[],world:[],arcs:[],chapters:[],timeline:[],relationships:[],notes:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||JSON.parse(localStorage.getItem('story-forge-v2')||'null')||JSON.parse(localStorage.getItem('story-forge-v1')||'null')||DEFAULT;
Object.keys(DEFAULT).forEach(k=>{if(!Array.isArray(db[k]))db[k]=[]});
let view='dashboard';
const main=document.getElementById('main');
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function id(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function ensureIds(){Object.values(db).forEach(arr=>arr.forEach(x=>{if(!x.id)x.id=id()}));save()}
ensureIds();
function stat(k){return db[k].length}
function allEntities(){return Object.entries(db).filter(([k])=>DEFAULT[k]).flatMap(([type,arr])=>arr.map(x=>({type,id:x.id,name:x.name||x.title||'بدون اسم'})))}
function entityName(entityId){return allEntities().find(x=>x.id===entityId)?.name||'غير معروف'}
function section(label,key,icon,desc){const arr=db[key];return `<div class="card"><div class="row"><b>${icon} ${label}</b><span class="pill">${arr.length}</span></div><p class="muted">${desc}</p>${arr.slice(-3).reverse().map(x=>`<div class="item"><b>${esc(x.name||x.title||'بدون اسم')}</b><div class="muted">${esc(x.desc||x.text||x.summary||'')}</div></div>`).join('')||'<div class="empty">لا توجد عناصر بعد</div>'}</div>`}
function render(){document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(view==='dashboard')renderDashboard();else if(view==='continuity')renderContinuity();else if(view==='export')renderExport();else if(view==='graph')renderGraph();else renderList()}
function renderDashboard(){const total=Object.values(db).reduce((a,v)=>a+v.length,0);main.innerHTML=`<section class="hero"><div><div class="eyebrow">STORY FORGE · CONTROL ROOM</div><h2>حوّل عالمك إلى منظومة قابلة للإدارة.</h2><div class="muted">ابنِ العالم، اربط الشخصيات، خطط الآركات، واكتشف مشاكل الاستمرارية.</div></div></section><div class="grid"><div class="card"><span class="muted">الشخصيات</span><div class="stat">${stat('characters')}</div></div><div class="card"><span class="muted">العالم</span><div class="stat">${stat('world')}</div></div><div class="card"><span class="muted">الآركات</span><div class="stat">${stat('arcs')}</div></div><div class="card"><span class="muted">الفصول</span><div class="stat">${stat('chapters')}</div></div><div class="card"><span class="muted">الأحداث</span><div class="stat">${stat('timeline')}</div></div><div class="card"><span class="muted">العلاقات</span><div class="stat">${stat('relationships')}</div></div></div><h3 class="section-title">موسوعة القصة · ${total} عنصر</h3><div class="grid">${section('الشخصيات','characters','👤','أبطال، خصوم، أهداف، أسرار وتطورات.')}${section('العالم','world','🌍','ممالك، مدن، قبائل، أنظمة وأفكار.')}${section('الآركات','arcs','⚔️','الصراعات الكبرى ونقاط التحول.')}${section('الفصول','chapters','📖','المشاهد والفصول بترتيبها.')}${section('العلاقات','relationships','🔗','روابط الشخصيات والمنظمات والأماكن.')}${section('الخط الزمني','timeline','◷','الأحداث وترتيبها وتأثيراتها.')}</div>`}
const MAP={characters:['الشخصيات','👤','اسم الشخصية','الوصف','الهدف، السر، نقطة الضعف، التطور'],world:['العالم','🌍','اسم العنصر','التعريف','التاريخ والقواعد والمعلومات المهمة'],arcs:['الآركات','⚔️','اسم الآرك','هدف الآرك','الصراع ونقطة التحول والنهاية'],chapters:['الفصول','📖','عنوان الفصل','ملخص الفصل','المشهد، الشخصيات الموجودة، النتيجة'],timeline:['الخط الزمني','◷','عنوان الحدث','ماذا حدث؟','الزمن/المكان وتأثير الحدث'],relationships:['العلاقات','🔗','نوع العلاقة','وصف العلاقة','اربط طرفين من موسوعتك'],notes:['الملاحظات','✎','عنوان الملاحظة','المحتوى','أفكار مستقبلية وتذكيرات']};
function renderList(){const [title,icon,ph1,ph2,meta]=MAP[view];let arr=db[view];if(view==='timeline')arr=[...arr].sort((a,b)=>(a.order??9999)-(b.order??9999));main.innerHTML=`<section class="hero"><div><div class="eyebrow">${title.toUpperCase()}</div><h2>${icon} ${title}</h2><div class="muted">${meta}</div></div></section><div class="toolbar"><input id="search" class="search" placeholder="ابحث في ${title}..."/><button class="add" id="add">+ إضافة</button></div><div id="list">${listItems(arr)}</div>`;document.getElementById('add').onclick=()=>editor(ph1,ph2,null,meta);document.getElementById('search').oninput=e=>{const q=e.target.value.toLowerCase();document.getElementById('list').innerHTML=listItems(arr,q)}}
function listItems(arr,q=''){return arr.map((x,i)=>({...x,_i:db[view].indexOf(x)})).filter(x=>(x.name||x.title||'').toLowerCase().includes(q)||(x.desc||x.text||x.summary||x.meta||'').toLowerCase().includes(q)).map(x=>`<div class="card" style="margin-bottom:10px"><div class="row"><div><b>${esc(x.name||x.title)}</b><div class="muted">${esc(x.desc||x.text||x.summary||'')}</div>${view==='relationships'?`<small class="muted">${esc(entityName(x.from))} ↔ ${esc(entityName(x.to))}</small>`:''}${view==='timeline'?`<small class="muted">ترتيب: ${esc(x.order??'—')}</small>`:''}</div><div class="actions"><button class="ghost" onclick="openEdit(${x._i})">فتح</button><button class="danger" onclick="removeItem(${x._i})">حذف</button></div></div></div>`).join('')||'<div class="empty">لا توجد نتائج.</div>'}
function entityOptions(selected=''){return `<option value="">اختر...</option>`+allEntities().map(e=>`<option value="${e.id}" ${e.id===selected?'selected':''}>${esc(e.name)} · ${esc(e.type)}</option>`).join('')}
function editor(ph1,ph2,idx=null,metaHint=''){const item=idx!==null?db[view][idx]:{};const rel=view==='relationships';const character=view==='characters';const timeline=view==='timeline';main.innerHTML=`<section class="hero"><div><div class="eyebrow">EDITOR</div><h2>${idx===null?'إضافة عنصر':'تعديل عنصر'}</h2><div class="muted">${esc(metaHint)}</div></div></section><div class="card editor"><input id="name" placeholder="${esc(ph1)}" value="${esc(item.name||item.title||'')}"><textarea id="desc" placeholder="${esc(ph2)}">${esc(item.desc||item.text||item.summary||'')}</textarea>${character?`<div class="two"><input id="role" placeholder="الدور (بطل/خصم/ثانوي...)" value="${esc(item.role||'')}"><input id="status" placeholder="الحالة" value="${esc(item.status||'')}"></div>`:''}${timeline?`<div class="two"><input id="order" type="number" placeholder="ترتيب زمني" value="${esc(item.order??'')}"><input id="place" placeholder="المكان" value="${esc(item.place||'')}"></div>`:''}${rel?`<div class="two"><select id="from">${entityOptions(item.from)}</select><select id="to">${entityOptions(item.to)}</select></div>`:''}<textarea id="meta" placeholder="تفاصيل إضافية">${esc(item.meta||'')}</textarea><div class="actions"><button class="save" id="save">حفظ</button><button class="ghost" id="cancel">إلغاء</button></div></div>`;document.getElementById('save').onclick=()=>{const o={...item,id:item.id||id(),name:document.getElementById('name').value.trim(),desc:document.getElementById('desc').value.trim(),meta:document.getElementById('meta').value.trim()};if(character){o.role=document.getElementById('role').value.trim();o.status=document.getElementById('status').value.trim()}if(timeline){o.order=Number(document.getElementById('order').value)||0;o.place=document.getElementById('place').value.trim()}if(rel){o.from=document.getElementById('from').value;o.to=document.getElementById('to').value;if(!o.from||!o.to)return alert('اختر الطرفين أولًا.')}if(!o.name)return alert('اكتب اسمًا أولًا.');if(idx===null)db[view].push(o);else db[view][idx]=o;save();render()};document.getElementById('cancel').onclick=render}
function openEdit(i){const [title,icon,ph1,ph2,meta]=MAP[view];editor(ph1,ph2,i,meta)}
function removeItem(i){if(confirm('حذف هذا العنصر؟')){db[view].splice(i,1);save();render()}}
function renderContinuity(){const issues=[];const names=db.characters.map(x=>(x.name||'').trim()).filter(Boolean);const seen=new Set();names.forEach(n=>{const key=n.toLowerCase();if(seen.has(key))issues.push(`اسم شخصية مكرر: ${n}`);seen.add(key)});db.chapters.forEach((c,i)=>{if(!(c.desc||'').trim())issues.push(`الفصل ${i+1}: لا يوجد ملخص.`)});db.timeline.forEach((e,i)=>{if(!e.name||!(e.desc||'').trim())issues.push(`حدث ${i+1}: بيانات ناقصة.`)});db.relationships.forEach((r,i)=>{if(r.from===r.to)issues.push(`العلاقة ${i+1}: الطرفان متطابقان.`);if(!r.from||!r.to)issues.push(`العلاقة ${i+1}: طرف مفقود.`)});const orphan=allEntities().filter(e=>e.type==='characters'&&!db.relationships.some(r=>r.from===e.id||r.to===e.id));main.innerHTML=`<section class="hero"><div><div class="eyebrow">CONTINUITY CHECK</div><h2>🔎 مدقق الاستمرارية</h2><div class="muted">فحص آلي للبيانات. الهدف اكتشاف إشارات تستحق مراجعتك، وليس الحكم على جودة السرد.</div></div></section><div class="grid"><div class="card"><b>مشكلات مكتشفة</b><div class="stat">${issues.length}</div></div><div class="card"><b>شخصيات بلا علاقات</b><div class="stat">${orphan.length}</div></div><div class="card"><b>فصول بلا ملخص</b><div class="stat">${db.chapters.filter(c=>!(c.desc||'').trim()).length}</div></div></div><h3 class="section-title">نتائج الفحص</h3><div class="card">${issues.length?issues.map(x=>`<div class="item">⚠️ ${esc(x)}</div>`).join(''):'<div class="item good">✅ لا توجد مشكلات بنيوية واضحة.</div>'}</div>${orphan.length?`<h3 class="section-title">شخصيات غير مرتبطة</h3><div class="card">${orphan.map(x=>`<div class="item">👤 ${esc(x.name)}</div>`).join('')}</div>`:''}`}
function renderGraph(){const rel=db.relationships;const nodes=allEntities().filter(e=>rel.some(r=>r.from===e.id||r.to===e.id)).slice(0,40);const cols=2;const w=760,h=Math.max(360,Math.ceil(nodes.length/cols)*90);const pos={};nodes.forEach((n,i)=>pos[n.id]={x:80+(i%cols)*340,y:50+Math.floor(i/cols)*90});main.innerHTML=`<section class="hero"><div><div class="eyebrow">RELATION MAP</div><h2>🕸️ شبكة العلاقات</h2><div class="muted">تصوير سريع للروابط التي سجلتها بين عناصر عالمك.</div></div></section><div class="card graph-wrap"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="شبكة العلاقات">${rel.map(r=>{const a=pos[r.from],b=pos[r.to];return a&&b?`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="currentColor" opacity=".35"/><text x="${(a.x+b.x)/2}" y="${(a.y+b.y)/2-6}" text-anchor="middle" fill="currentColor" opacity=".7" font-size="11">${esc(r.name||'علاقة')}</text>`:''}).join('')}${nodes.map(n=>`<g><circle cx="${pos[n.id].x}" cy="${pos[n.id].y}" r="28" fill="currentColor" opacity=".12" stroke="currentColor"/><text x="${pos[n.id].x}" y="${pos[n.id].y+4}" text-anchor="middle" fill="currentColor" font-size="11">${esc(n.name).slice(0,18)}</text></g>`).join('')}</svg></div>`}
function renderExport(){main.innerHTML=`<section class="hero"><div><div class="eyebrow">BACKUP</div><h2>💾 النسخ الاحتياطي</h2><div class="muted">احفظ عالمك خارج المتصفح أو استعد نسخة سابقة.</div></div></section><div class="grid"><div class="card"><b>تصدير</b><p class="muted">ملف JSON كامل قابل للحفظ.</p><button class="add" id="download">تنزيل النسخة</button></div><div class="card"><b>استيراد</b><p class="muted">استعادة نسخة Story Forge محفوظة سابقًا.</p><input id="import" type="file" accept="application/json"></div></div>`;document.getElementById('download').onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='story-forge-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};document.getElementById('import').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const incoming=JSON.parse(reader.result);if(!incoming||typeof incoming!=='object')throw Error();Object.keys(DEFAULT).forEach(k=>{if(Array.isArray(incoming[k]))db[k]=incoming[k]});ensureIds();save();render();alert('تم استيراد النسخة بنجاح.')}catch(err){alert('ملف غير صالح.')}};reader.readAsText(file)}}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{view=n.dataset.view;render()});document.getElementById('newBtn').onclick=()=>{view='characters';editor('اسم الشخصية','وصف الشخصية',null,'ابدأ بالشخصية ثم أضف هدفها وسرها وتطورها.')};window.openEdit=openEdit;window.removeItem=removeItem;render();