const KEY='story-forge-v2';
const DEFAULT={characters:[],world:[],arcs:[],chapters:[],timeline:[],relationships:[],notes:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||JSON.parse(localStorage.getItem('story-forge-v1')||'null')||DEFAULT;
Object.keys(DEFAULT).forEach(k=>{if(!Array.isArray(db[k]))db[k]=[]});
let view='dashboard';
const main=document.getElementById('main');
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function stat(k){return db[k].length}
function section(label,key,icon,desc){const arr=db[key];return `<div class="card"><div class="row"><b>${icon} ${label}</b><span class="pill">${arr.length}</span></div><p class="muted">${desc}</p>${arr.slice(-3).reverse().map(x=>`<div class="item"><b>${esc(x.name||x.title||'بدون اسم')}</b><div class="muted">${esc(x.desc||x.text||x.summary||'')}</div></div>`).join('')||'<div class="empty">لا توجد عناصر بعد</div>'}</div>`}
function render(){document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(view==='dashboard')renderDashboard();else if(view==='continuity')renderContinuity();else if(view==='export')renderExport();else renderList()}
function renderDashboard(){main.innerHTML=`<section class="hero"><div><div class="eyebrow">STORY FORGE · CONTROL ROOM</div><h2>حوّل عالمك إلى منظومة قابلة للإدارة.</h2><div class="muted">الشخصيات، العالم، الآركات، الفصول، العلاقات والخط الزمني في مكان واحد.</div></div></section><div class="grid"><div class="card"><span class="muted">الشخصيات</span><div class="stat">${stat('characters')}</div></div><div class="card"><span class="muted">العالم</span><div class="stat">${stat('world')}</div></div><div class="card"><span class="muted">الآركات</span><div class="stat">${stat('arcs')}</div></div><div class="card"><span class="muted">الفصول</span><div class="stat">${stat('chapters')}</div></div></div><h3 class="section-title">موسوعة القصة</h3><div class="grid">${section('الشخصيات','characters','👤','أبطال، خصوم، أهداف، أسرار وتطورات.')}${section('العالم','world','🌍','ممالك، مدن، قبائل، أنظمة وأفكار.')}${section('الآركات','arcs','⚔️','الصراعات الكبرى ونقاط التحول.')}${section('الفصول','chapters','📖','المشاهد والفصول بترتيبها.')}${section('العلاقات','relationships','🔗','روابط الشخصيات والمنظمات والأماكن.')}${section('الخط الزمني','timeline','◷','الأحداث وترتيبها.')}</div>`}
const MAP={characters:['الشخصيات','👤','اسم الشخصية','الوصف','الهدف، السر، نقطة الضعف، التطور'],world:['العالم','🌍','اسم العنصر','التعريف','التاريخ والقواعد والمعلومات المهمة'],arcs:['الآركات','⚔️','اسم الآرك','هدف الآرك','الصراع ونقطة التحول والنهاية'],chapters:['الفصول','📖','عنوان الفصل','ملخص الفصل','المشهد، الشخصيات الموجودة، النتيجة'],timeline:['الخط الزمني','◷','عنوان الحدث','ماذا حدث؟','الزمن/المكان وتأثير الحدث'],relationships:['العلاقات','🔗','نوع العلاقة','وصف العلاقة','الطرف الأول ↔ الطرف الثاني'],notes:['الملاحظات','✎','عنوان الملاحظة','المحتوى','أفكار مستقبلية وتذكيرات']};
function renderList(){const [title,icon,ph1,ph2,meta]=MAP[view];const arr=db[view];main.innerHTML=`<section class="hero"><div><div class="eyebrow">${title.toUpperCase()}</div><h2>${icon} ${title}</h2><div class="muted">${meta}</div></div></section><div class="toolbar"><input id="search" class="search" placeholder="ابحث في ${title}..."/><button class="add" id="add">+ إضافة</button></div><div id="list">${listItems(arr)}</div>`;document.getElementById('add').onclick=()=>editor(ph1,ph2,null,meta);document.getElementById('search').oninput=e=>{const q=e.target.value.toLowerCase();document.getElementById('list').innerHTML=listItems(arr,q)}}
function listItems(arr,q=''){return arr.map((x,i)=>({...x,_i:i})).filter(x=>(x.name||x.title||'').toLowerCase().includes(q)||(x.desc||x.text||x.summary||x.meta||'').toLowerCase().includes(q)).map(x=>`<div class="card" style="margin-bottom:10px"><div class="row"><div><b>${esc(x.name||x.title)}</b><div class="muted">${esc(x.desc||x.text||x.summary||'')}</div></div><div class="actions"><button class="ghost" onclick="openEdit(${x._i})">فتح</button><button class="danger" onclick="removeItem(${x._i})">حذف</button></div></div></div>`).join('')||'<div class="empty">لا توجد نتائج.</div>'}
function editor(ph1,ph2,idx=null,metaHint=''){const item=idx!==null?db[view][idx]:{};main.innerHTML=`<section class="hero"><div><div class="eyebrow">EDITOR</div><h2>${idx===null?'إضافة عنصر':'تعديل عنصر'}</h2><div class="muted">${esc(metaHint)}</div></div></section><div class="card editor"><input id="name" placeholder="${esc(ph1)}" value="${esc(item.name||item.title||'')}"><textarea id="desc" placeholder="${esc(ph2)}">${esc(item.desc||item.text||item.summary||'')}</textarea><textarea id="meta" placeholder="تفاصيل إضافية">${esc(item.meta||'')}</textarea><div class="actions"><button class="save" id="save">حفظ</button><button class="ghost" id="cancel">إلغاء</button></div></div>`;document.getElementById('save').onclick=()=>{const o={name:document.getElementById('name').value.trim(),desc:document.getElementById('desc').value.trim(),meta:document.getElementById('meta').value.trim()};if(!o.name)return alert('اكتب اسمًا أولًا.');if(idx===null)db[view].push(o);else db[view][idx]={...db[view][idx],...o};save();render()};document.getElementById('cancel').onclick=render}
function openEdit(i){const [title,icon,ph1,ph2,meta]=MAP[view];editor(ph1,ph2,i,meta)}
function removeItem(i){if(confirm('حذف هذا العنصر؟')){db[view].splice(i,1);save();render()}}
function renderContinuity(){const issues=[];const names=db.characters.map(x=>(x.name||'').trim()).filter(Boolean);db.chapters.forEach((c,i)=>{const text=(c.desc||c.meta||'').toLowerCase();names.forEach(n=>{if(text.includes(n.toLowerCase())){const count=names.filter(other=>other!==n&&text.includes(other.toLowerCase())).length;if(count>8)issues.push(`الفصل ${i+1}: يحتوي على عدد كبير من الشخصيات؛ راجع المشهد حتى لا يصبح مزدحمًا.`)}})});const duplicate=[...new Set(names.filter((n,i)=>names.indexOf(n)!==i))];main.innerHTML=`<section class="hero"><div><div class="eyebrow">CONTINUITY CHECK</div><h2>🔎 مدقق الاستمرارية</h2><div class="muted">فحص أولي آلي للبيانات التي أدخلتها. ليس بديلًا عن المراجعة السردية البشرية.</div></div></section><div class="grid"><div class="card"><b>أسماء شخصيات مكررة</b><p class="muted">${duplicate.length?duplicate.map(esc).join('، '):'لا توجد'}</p></div><div class="card"><b>فصول بلا ملخص</b><p class="muted">${db.chapters.filter(c=>!(c.desc||'').trim()).length}</p></div><div class="card"><b>أحداث بلا وصف</b><p class="muted">${db.timeline.filter(c=>!(c.desc||'').trim()).length}</p></div></div><h3 class="section-title">ملاحظات المدقق</h3><div class="card">${issues.length?issues.map(x=>`<div class="item">⚠️ ${esc(x)}</div>`).join(''):'✅ لا توجد إشارات أولية واضحة في البيانات الحالية.'}</div>`}
function renderExport(){main.innerHTML=`<section class="hero"><div><div class="eyebrow">BACKUP</div><h2>💾 تصدير عالمك</h2><div class="muted">أنشئ نسخة JSON كاملة من بيانات قصتك.</div></div></section><div class="card"><p>عدد العناصر: ${Object.values(db).reduce((a,v)=>a+v.length,0)}</p><button class="add" id="download">تنزيل نسخة احتياطية</button></div>`;document.getElementById('download').onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='story-forge-backup.json';a.click();URL.revokeObjectURL(a.href)}}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{view=n.dataset.view;render()});document.getElementById('newBtn').onclick=()=>{view='characters';editor('اسم الشخصية','وصف الشخصية',null,'ابدأ بالشخصية ثم أضف هدفها وسرها وتطورها.')};window.openEdit=openEdit;window.removeItem=removeItem;render();