const KEY='story-forge-v3';
const DRAFT='story-forge-draft';const REV='story-forge-revision';const VERS='story-forge-versions';
const DEFAULT={characters:[],world:[],arcs:[],chapters:[],timeline:[],relationships:[],notes:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||DEFAULT;Object.keys(DEFAULT).forEach(k=>{if(!Array.isArray(db[k]))db[k]=[]});
const $=id=>document.getElementById(id);const fields=['title','chapter','location','draft'];
function stats(){const t=$('draft').value,trimmed=t.trim();const words=trimmed?trimmed.split(/\s+/).length:0;$('words').textContent=words;$('chars').textContent=t.length;$('paragraphs').textContent=trimmed?trimmed.split(/\n\s*\n/).filter(Boolean).length:0;$('reading').textContent=words?`${Math.max(1,Math.ceil(words/220))} د`:'0 د'}
function setStatus(text){$('saved').textContent=text}
function snapshot(){return {title:$('title').value,chapter:$('chapter').value,location:$('location').value,draft:$('draft').value,revision:$('revision').value,updatedAt:new Date().toISOString()}}
function persistDraft(manual=false){localStorage.setItem(DRAFT,JSON.stringify(snapshot()));setStatus(manual?'تم حفظ المسودة ✓':'حفظ تلقائي ✓')}
function saveVersion(){const versions=JSON.parse(localStorage.getItem(VERS)||'[]');const s=snapshot();versions.unshift(s);localStorage.setItem(VERS,JSON.stringify(versions.slice(0,10)));setStatus('تم إنشاء نسخة مراجعة ✓')}
function persistRevision(){localStorage.setItem(REV,$('revision').value)}
function load(){const x=JSON.parse(localStorage.getItem(DRAFT)||'null');if(x){fields.forEach(k=>$(k).value=x[k]||'');if(x.revision&&!localStorage.getItem(REV))localStorage.setItem(REV,x.revision);setStatus('استُعيدت آخر مسودة')}$('revision').value=localStorage.getItem(REV)||'';stats()}
function analyze(){const t=$('draft').value.trim();if(!t){$('analysis').textContent='اكتب نصًا أولًا ثم حلله.';return}const words=t.split(/\s+/).filter(Boolean);const lines=t.split(/\n/);const dialogue=(t.match(/["“”«»].*?["“”«»]/g)||[]).join(' ');const sentences=(t.match(/[.!؟!?]+/g)||[]).length;const paragraphs=t.split(/\n\s*\n/).filter(x=>x.trim()).length;const freq={};words.map(w=>w.toLowerCase().replace(/[^\u0600-\u06FF\w]/g,'')).filter(w=>w.length>3).forEach(w=>freq[w]=(freq[w]||0)+1);const repeated=Object.entries(freq).filter(([,n])=>n>=5).sort((a,b)=>b[1]-a[1]).slice(0,8);$('analysis').innerHTML=`<div class="grid"><div class="item"><span class="muted">الجمل التقريبية</span><strong>${sentences}</strong></div><div class="item"><span class="muted">الأسطر</span><strong>${lines.length}</strong></div><div class="item"><span class="muted">الحوار المقتبس</span><strong>${dialogue?dialogue.split(/\s+/).length:0} كلمة</strong></div><div class="item"><span class="muted">الفقرات</span><strong>${paragraphs}</strong></div></div><div class="item"><b>تكرار مرتفع محتمل:</b> ${repeated.length?repeated.map(([w,n])=>`${w} (${n})`).join(' · '):'لا توجد كلمات بارزة بالتكرار.'}</div>`}
function showVersions(){const versions=JSON.parse(localStorage.getItem(VERS)||'[]');if(!versions.length)return alert('لا توجد نسخ محفوظة بعد.');const choice=prompt(versions.map((v,i)=>`${i+1}. ${v.title||'بدون عنوان'} — ${new Date(v.updatedAt).toLocaleString('ar')}`).join('\n')+'\n\nاكتب رقم النسخة للاستعادة:');const n=Number(choice)-1;if(Number.isInteger(n)&&versions[n]){const v=versions[n];fields.forEach(k=>$(k).value=v[k]||'');$('revision').value=v.revision||'';stats();persistDraft(true)}}
let timer;fields.forEach(k=>$(k).addEventListener('input',()=>{stats();clearTimeout(timer);timer=setTimeout(()=>persistDraft(false),500)}));
$('revision').addEventListener('input',persistRevision);$('analyze').onclick=analyze;$('saveDraft').onclick=()=>persistDraft(true);$('saveVersion').onclick=saveVersion;$('versions').onclick=showVersions;
$('save').onclick=()=>{const title=$('title').value.trim(),draft=$('draft').value.trim();if(!title||!draft)return alert('اكتب عنوانًا ومحتوى الفصل أولًا.');db.chapters.push({id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36),name:title,desc:draft,meta:`الفصل: ${$('chapter').value.trim()} | المكان/الزمن: ${$('location').value.trim()}`,chapter:$('chapter').value.trim(),location:$('location').value.trim(),revision:$('revision').value,createdAt:new Date().toISOString()});localStorage.setItem(KEY,JSON.stringify(db));localStorage.removeItem(DRAFT);setStatus('تم حفظ النص كفصل ✓')};
$('clear').onclick=()=>{if(confirm('بدء مسودة جديدة؟ سيتم حذف المسودة الحالية من هذا المتصفح.')){fields.forEach(k=>$(k).value='');$('revision').value='';localStorage.removeItem(DRAFT);localStorage.removeItem(REV);stats();$('analysis').textContent='اضغط تحليل النص للحصول على مؤشرات عن السرد والحوار والتكرار.';setStatus('مسودة جديدة')}};
$('clearRevision').onclick=()=>{$('revision').value='';localStorage.removeItem(REV);setStatus('تم مسح ملاحظات المراجعة')};
$('download').onclick=()=>{const text=`${$('title').value.trim()}\n${$('chapter').value.trim()}${$('location').value.trim()?' · '+$('location').value.trim():''}\n\n${$('draft').value}\n\n--- ملاحظات المراجعة ---\n${$('revision').value}`;const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(($('title').value.trim()||'story')+'.txt').replace(/[\\/:*?"<>|]/g,'-');a.click();URL.revokeObjectURL(a.href);setStatus('تم تصدير TXT ✓')};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();persistDraft(true)}});load();