const KEY='story-forge-draft-v2',VERS='story-forge-versions-v2',REV='story-forge-revision-v2';const $=id=>document.getElementById(id);const fields=['title','chapter','location','goal','tag','arc','chapterId','locationId','eventId','draft'];let past=[],future=[],timer;
function count(){const t=$('draft').value.trim();return t?t.split(/\s+/).length:0}function stats(){const t=$('draft').value.trim(),w=count(),g=Number($('goal').value)||0;$('words').textContent=w;$('chars').textContent=$('draft').value.length;$('paragraphs').textContent=t?t.split(/\n\s*\n/).filter(Boolean).length:0;$('reading').textContent=w?`${Math.max(1,Math.ceil(w/220))} د`:'0 د';$('goalText').textContent=g?`${w} / ${g} كلمة`:'لا يوجد هدف';$('goalBar').style.width=g?`${Math.min(100,Math.round(w/g*100))}%`:'0%'}
function snap(){const o={};fields.forEach(k=>o[k]=$.call?$(k).value:document.getElementById(k)?.value||'');o.revision=$('revision').value;o.updatedAt=new Date().toISOString();return o}function apply(x){fields.forEach(k=>{if($(k))$(k).value=x[k]||''});$('revision').value=x.revision||'';stats();links();continuity()}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(snap()));localStorage.setItem(REV,$('revision').value);$('saved').textContent='حفظ تلقائي ✓'}
function remember(){past.push(JSON.stringify(snap()));if(past.length>30)past.shift();future=[]}
function undo(){if(!past.length)return;future.push(JSON.stringify(snap()));apply(JSON.parse(past.pop()))}function redo(){if(!future.length)return;past.push(JSON.stringify(snap()));apply(JSON.parse(future.pop()))}
function populate(){const add=(id,arr,sel)=>{const e=$(id);arr.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.name||x.title||'بدون اسم';if(x.id===sel)o.selected=true;e.appendChild(o)})};const d=JSON.parse(localStorage.getItem(KEY)||'null');let x=JSON.parse(localStorage.getItem('story-forge-draft-v2')||'null');const source=x||d;add('arc',StoryForge.db.arcs,source?.arc);add('chapterId',StoryForge.db.chapters,source?.chapterId);add('locationId',StoryForge.db.locations,source?.locationId);add('eventId',StoryForge.db.events,source?.eventId);if(source)apply(source)}
function saveVersion(){const v=JSON.parse(localStorage.getItem(VERS)||'[]');v.unshift(snap());localStorage.setItem(VERS,JSON.stringify(v.slice(0,20)));$('saved').textContent='تم إنشاء نسخة ✓'}
function restore(){const v=JSON.parse(localStorage.getItem(VERS)||'[]');if(!v.length)return alert('لا توجد نسخ.');const n=Number(prompt(v.map((x,i)=>`${i+1}. ${x.title||'بدون عنوان'} — ${new Date(x.updatedAt).toLocaleString('ar')}`).join('\n')+'\n\nرقم النسخة:'))-1;if(v[n]){remember();apply(v[n]);saveLocal()}}
function analyze(){const t=$('draft').value.trim();if(!t)return $('analysis').textContent='اكتب النص أولًا.';const chars=StoryForge.db.characters.filter(c=>c.name&&new RegExp(c.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i').test(t));const sentences=(t.match(/[.!؟!?]+/g)||[]).length;const dialogue=(t.match(/["“”«»].*?["“”«»]/g)||[]).join(' ');$('analysis').innerHTML=`<div class="grid"><div class="item"><span class="muted">الجمل</span><strong>${sentences}</strong></div><div class="item"><span class="muted">الحوار</span><strong>${dialogue?dialogue.split(/\s+/).length:0} كلمة</strong></div><div class="item"><span class="muted">الشخصيات المكتشفة</span><strong>${chars.length}</strong></div></div><div class="item">${chars.length?chars.map(c=>c.name).join(' · '):'لم تظهر أسماء شخصيات مسجلة.'}</div>`}
function continuity(){const t=$('draft').value;const issues=StoryForge.continuity();const names=StoryForge.db.characters.filter(c=>c.name&&!new RegExp(c.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i').test(t)).slice(0,10);$('continuityResult').innerHTML=`${issues.length?issues.slice(0,8).map(x=>`<div class="item">⚠️ ${x.message}</div>`).join(''):'<div class="item good">✅ لا توجد مشاكل بنيوية معروفة.</div>'}${names.length?`<div class="item"><b>شخصيات مسجلة لم تظهر:</b> ${names.map(c=>c.name).join('، ')}</div>`:''}`}
function links(){const ids=[['Arc',$('arc').value],['Chapter',$('chapterId').value],['Location',$('locationId').value],['Event',$('eventId').value]].filter(x=>x[1]);$('links').innerHTML=ids.length?ids.map(([l,i])=>`<div class="item"><b>${l}</b> · ${StoryForge.name(i)}</div>`).join(''):'لا توجد روابط محددة.'}
function focus(){document.body.classList.toggle('focus-mode');$('focus').textContent=document.body.classList.contains('focus-mode')?'خروج من التركيز':'وضع التركيز';$('draft').focus()}
fields.forEach(k=>$(k)?.addEventListener('input',()=>{remember();stats();links();clearTimeout(timer);timer=setTimeout(saveLocal,400)}));$('revision').addEventListener('input',saveLocal);$('saveDraft').onclick=()=>{saveLocal();$('saved').textContent='تم حفظ المسودة ✓'};$('saveVersion').onclick=saveVersion;$('versions').onclick=restore;$('undo').onclick=undo;$('redo').onclick=redo;$('focus').onclick=focus;$('analyze').onclick=analyze;$('continuity').onclick=continuity;$('refreshLinks').onclick=links;$('clearRevision').onclick=()=>{$('revision').value='';saveLocal()};$('clear').onclick=()=>{if(confirm('بدء مسودة جديدة؟')){remember();fields.forEach(k=>$(k).value='');$('revision').value='';stats();links();}};
$('save').onclick=()=>{const title=$('title').value.trim(),text=$('draft').value.trim();if(!title||!text)return alert('اكتب العنوان والنص أولًا.');const c=StoryForge.create('chapters',{name:title,number:Number($('chapter').value)||0,arcId:$('arc').value,chapterLinkId:$('chapterId').value,locationId:$('locationId').value,eventIds:$('eventId').value?[ $('eventId').value ]:[],goal:$('goal').value,tag:$('tag').value,text,revision:$('revision').value,createdAt:new Date().toISOString()});$('saved').textContent='تم حفظ الفصل في قاعدة القصة ✓';localStorage.removeItem(KEY);try{localStorage.removeItem('story-forge-draft-v2')}catch{};alert(`تم حفظ الفصل: ${c.name}`)};
$('download').onclick=()=>{const text=`${$('title').value.trim()}\n\n${$('draft').value}\n\n--- ملاحظات المراجعة ---\n${$('revision').value}`;const b=new Blob([text],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=(($('title').value.trim()||'story')+'.txt').replace(/[\\/:*?"<>|]/g,'-');a.click()};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveLocal()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}if(e.key==='Escape'&&document.body.classList.contains('focus-mode'))focus()});populate();stats();links();continuity();